### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by jimmycuadra** [rustless/valico#13]
Hello! I was hoping to use Valico to generate Rust source code with types defined in JSON Schema files, but I'm having trouble understanding the details of how to use the library for this purpose. It would be really helpful if API documentation was added for the various types and functions Valico provides. In many cases it's not clear what a function does, how it differs from a similarly named function, or the meaning/purpose of a function's arguments. Thanks for your work on this project—it may prove very useful for me!

**Comment by s-panferov** [comment]
@jimmycuadra `valico` is just a validation tool, not a code generator. I can validate you JSON's according to schema or DSL spec, nothing more.

I'll try to elaborate this in docs.

**Comment by jimmycuadra** [comment]
Yes, I understand that, but it does allow me to transform JSON data from a file into a `Schema` value. I was hoping to build the code generation part myself by iterating through that value.

**Comment by s-panferov** [comment]
@jimmycuadra could you explain more what kind of tool do you need? What kind of code you want to generate? Maybe I can make it easier for you.

**Comment by jimmycuadra** [comment]
I have a collection of JSON Schema files that describe data types in a program. My goal is to automatically generate Rust code that defines these types. For example, given this JSON Schema:

``` json
{
  "type": "object",
  "title": "Person",
  "description": "A human being",
  "properties": {
    "name": {
      "type": "string",
      "description": "The person's name"
    },
    "age": {
      "type": "number",
      "description": "The person's age",
      "minimum": 0
    },
    "sex": {
      "type": "string",
      "description": "The person's sex",
      "enum": ["female", "male"]
  }
}
```

I'd want to generate Rust code along the lines of:

``` rust
/// A human being
pub struct Person {
    /// The person's name
    pub name: String,
    /// The person's age
    pub age: u64,
    /// The person's sex
    pub sex: Sex,
}

/// The person's sex
pub enum Sex {
    Female,
    Male,
}
```

**Comment by s-panferov** [comment]
I think this is out of scope right now. Schema is just a JSON, so you can extract values from it without any additional layer.
