### ISSUE TITLE
Sub-schema resolution

### ISSUE THREAD

**Issue by calebmer** [rustless/valico#15]
Hi, I'm evaluating using `valico` for a project I'm on or writing something in house. Is there any way in this library to select a schema for a sub property? For example in the following schema:

```json
{
  "type": "object",
  "properties": {
    "hello": {
      "type": "object",
      "properties": {
        "world": {
          "type": "string"
        }
      }
    }
  }
}
```

I could call a method like `resolve("/hello/world")` which would return the schema corresponding to:

```json
{
  "type": "string"
}
```

**Comment by s-panferov** [comment]
@calebmer could you please describe your use-case?

**Comment by calebmer** [comment]
I have a large JSON schema which describes the data structure of my REST API and when a developer navigates to a route, I'd like to get the schema for data at that route.
