### ISSUE TITLE
Using serde instead of rustc-serialize

### ISSUE THREAD

**Issue by calebmer** [rustless/valico#17]
It seems like [`serde`](https://crates.io/crates/serde) (and likewise [`serde_json`](https://crates.io/crates/serde_json)) is becoming the canonical way to serialize/deserialize JSON in rust. Even the `rustc-serialize` docs [say](https://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/index.html#the-status-of-this-library):

> While this library is the standard way of working with JSON in Rust, there is a next-generation library called Serde that's in the works (it's faster, overcomes some design limitations of rustc-serialize and has more features). You might consider using it when starting a new project or evaluating Rust JSON performance.

It would be helpful to everyone who is taking this recommendation and switching to `serde` if this library could either support both `serde` and `rustc-serialize`, or publish a version with only `serde` support.

**Comment by calebmer** [comment]
If this is something you are ok with, I can write a PR that implements both.

**Comment by antoine-de** [comment]
I think it would be very helpful indeed

**Comment by s-panferov** [comment]
@calebmer @antoine-de I'm OK with this, but this requires all the stack (rustless, valico, queryst) to be rewritten. I'm not sure that I can do it quickly, so some help definitely wanted.

**Comment by s-panferov** [comment]
Serde work started, I think that tomorrow everything will be ready.

**Comment by s-panferov** [comment]
@calebmer @antoine-de `1.0.0` version with Serde support was published yesterday, please try it. The are also several minor bugs fixed.

**Comment by antoine-de** [comment]
great !

I have some mixed dependency problems (my rustless's valico version is still on the 0.8.2), and I have some error when bumping the valico version in rustless.
I'll look into them tomorrow.

**Comment by chpio** [comment]
this can be closed, i guess?!

**Comment by s-panferov** [comment]
@chpio thanks
