### ISSUE TITLE
valico and threads

### ISSUE THREAD

**Issue by Fiedzia** [rustless/valico#22]
I've got something like this - trying to combine valico with iron:

`
lazy_static!{
    static ref classify_candidates_schema: ScopedSchema<'static> = read_json_schema("/schemas/schema.json").unwrap();
}

pub fn read_json_schema(path: &str) -> io::Result<ScopedSchema> {
    let mut buffer = String::new();

```
    let file = File::open(
    &Path::new(
        &format!(
            "{}{}",
            &Path::new(&env::current_exe().unwrap())
            .parent()
            .unwrap()
            .to_str()
            .unwrap(),
            path
        )
    )
).ok()
.unwrap();
file.read_to_string(&mut buffer).unwrap();

let json_schema: serde_json::value::Value = serde_json::from_str(&buffer).unwrap();

let mut scope = json_schema::Scope::new();
let schema = scope.compile_and_return(json_schema.clone(), true).ok().unwrap();
Ok(schema)
```

}
`
which doesn't compile due to:
`
error[E0277]: the trait bound `std::rc::Rc<valico::json_schema::keywords::KeywordConsumer>: core::marker::Sync` is not satisfied
 --> <lazy_static macros>:2:32
  |
2 | use std :: sync :: ONCE_INIT ; static mut $ NAME : $ crate :: lazy :: Lazy < $
  |                                ^
<lazy_static macros>:21:1: 21:40 note: in this expansion of __lazy_static_create! (defined in <lazy_static macros>)
<lazy_static macros>:4:1: 5:75 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
src/commands/webserver/request_handlers.rs:25:1: 27:2 note: in this expansion of lazy_static! (defined in <lazy_static macros>)
  |
  = note: `std::rc::Rc<valico::json_schema::keywords::KeywordConsumer>` cannot be shared between threads safely
  = note: required because of the requirements on the impl of `core::marker::Sync` for `std::collections::hash::table::RawTable<&'static str, std::rc::Rc<valico::json_schema::keywords::KeywordConsumer>>`
  = note: required because it appears within the type `std::collections::HashMap<&'static str, std::rc::Rc<valico::json_schema::keywords::KeywordConsumer>>`
  = note: required because it appears within the type `valico::json_schema::Scope`
  = note: required because it appears within the type `&'static valico::json_schema::Scope`
  = note: required because it appears within the type `valico::json_schema::schema::ScopedSchema<'static>`
  = note: required by `lazy_static::lazy::Lazy`

error: aborting due to previous error

`

Could it be fixed?

**Comment by goyox86** [comment]
Hi guys! Any way to make this work? Thanks   :)

**Comment by daddinuz** [comment]
Hi there, any update on this issue?
