### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by erickt** [rustless/valico#43]
Hello! I'm trying to clean up some of my dependencies, and I saw that the currently published valico is pulling in lazy_static 0.2.11, that is no longer used in the master branch. Could a new version be published without this dependency? I'd be happy to packport the patch if you aren't ready to release your other changes.

**Comment by s-panferov** [comment]
@erickt done, thanks for the reminder.

**Comment by erickt** [comment]
Thanks @s-panferov!
